# Generated by Django 3.1 on 2023-07-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query_type', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('perplexity_result', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('link2', models.URLField(blank=True, max_length=500, null=True)),
                ('link3', models.URLField(blank=True, max_length=500, null=True)),
                ('link4', models.URLField(blank=True, max_length=500, null=True)),
                ('links', models.URLField(blank=True, max_length=500, null=True)),
                ('softage_answer', models.TextField(blank=True, null=True)),
                ('assigned', models.BooleanField(default=False, null=True)),
                ('answer_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('fluency', models.IntegerField(blank=True, null=True)),
                ('perceived_utility', models.IntegerField(blank=True, null=True)),
                ('backed_by_citation', models.IntegerField(blank=True, null=True)),
                ('state_reg_citation', models.IntegerField(blank=True, null=True)),
                ('citation_precision', models.CharField(blank=True, max_length=10, null=True)),
                ('citation_feedback', models.CharField(blank=True, max_length=1000, null=True)),
                ('P_ID', models.IntegerField()),
            ],
        ),
    ]
