# Generated by Django 3.1 on 2023-07-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_answ_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='P_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
