# Generated by Django 3.1 on 2023-07-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ques_answ_app', '0002_auto_20230711_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='link',
            new_name='link1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='links',
            new_name='link5',
        ),
    ]
